### ISSUE TITLE
No License or 3rd Party Use Guidance

### ISSUE THREAD

**Issue by bbsdddougla** [DavidCBerry13/FoodTruckNationApi#2]
Hi David,
I attended your talk in January for the Wisconsin .NET Users Group and found it really helpful.

I'd like you use your code as the starting point for a commercial project I'm working on for a client.

Under what terms can I use your code?

**Comment by DavidCBerry13** [comment]
Hey,
Thanks for coming to my talk.  Sorry I didn't see this for a couple days, the notification landed in my spam folder.

I added the MIT license to the project which I think is pretty permissive in terms of letting people use this as a demo or a starting point for something else.

Thanks,
David

**Comment by bbsdddougla** [comment]
Thanks David,
Really appreciate you putting your code out here for other people to learn from.
BR,
Drew
